//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicUploader.DocutapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocutapService.IDocutap")]
    public interface IDocutap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocutap/DocutapMacro", ReplyAction="http://tempuri.org/IDocutap/DocutapMacroResponse")]
        string DocutapMacro(string filepath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocutapChannel : ClinicUploader.DocutapService.IDocutap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocutapClient : System.ServiceModel.ClientBase<ClinicUploader.DocutapService.IDocutap>, ClinicUploader.DocutapService.IDocutap {
        
        public DocutapClient() {
        }
        
        public DocutapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocutapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocutapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocutapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DocutapMacro(string filepath) {
            return base.Channel.DocutapMacro(filepath);
        }
    }
}
