//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicUploader.ClinicService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClinicService.IClinic")]
    public interface IClinic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClinic/MacroStriping", ReplyAction="http://tempuri.org/IClinic/MacroStripingResponse")]
        string MacroStriping(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClinic/UploadContent", ReplyAction="http://tempuri.org/IClinic/UploadContentResponse")]
        string UploadContent(string siteId, byte[] data, string FileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClinicChannel : ClinicUploader.ClinicService.IClinic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClinicClient : System.ServiceModel.ClientBase<ClinicUploader.ClinicService.IClinic>, ClinicUploader.ClinicService.IClinic {
        
        public ClinicClient() {
        }
        
        public ClinicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClinicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClinicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClinicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MacroStriping(string fileName) {
            return base.Channel.MacroStriping(fileName);
        }
        
        public string UploadContent(string siteId, byte[] data, string FileName) {
            return base.Channel.UploadContent(siteId, data, FileName);
        }
    }
}
